### ISSUE TITLE
unable to run libfuzzer: "-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer"

### ISSUE THREAD

**Issue by asarubbo** [facebook/zstd#1539]
Reproducer:

```
git clone https://github.com/facebook/zstd.git
cd zstd/tests/fuzz/
make corpora
make libFuzzer
./fuzz.py build all --enable-coverage --enable-asan --enable-ubsan --lib-fuzzing-engine Fuzzer/libFuzzer.a --cc clang --cxx clang++
./fuzz.py libfuzzer block_decompress -max_len=8192 -jobs=4
```

Result:
```
/tmp/zstd/tests/fuzz/block_decompress -artifact_prefix=/tmp/zstd/tests/fuzz/corpora/block_decompress-crash/ /tmp/zstd/tests/fuzz/corpora/block_decompress /tmp/zstd/tests/fuzz/corpora/block_decompress-crash -max_len=8192 -jobs=4
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
Traceback (most recent call last):
  File "./fuzz.py", line 821, in <module>
    sys.exit(main())
  File "./fuzz.py", line 802, in main
    return libfuzzer_cmd(args)
  File "./fuzz.py", line 522, in libfuzzer_cmd
    libfuzzer(args.TARGET, args.corpora, args.artifact, args.seed, args.extra)
  File "./fuzz.py", line 513, in libfuzzer
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/zstd/tests/fuzz/block_decompress', '-artifact_prefix=/tmp/zstd/tests/fuzz/corpora/block_decompress-crash/', '/tmp/zstd/tests/fuzz/corpora/block_decompress', '/tmp/zstd/tests/fuzz/corpora/block_decompress-crash', '-max_len=8192', '-jobs=4']' returned non-zero exit status 1.
```

**Comment by terrelln** [comment]
We need to keep around this method of building for oss-fuzzer, but I will add a flag `--enable-fuzzer` that can be used instead of `--enable-coverage --lib-fuzzing-engine Fuzzer/libfuzzer.a`, with a new enough `clang`.

**Comment by asarubbo** [comment]
Maybe you need to add it here too:
https://github.com/facebook/zstd/blob/dev/tests/fuzz/README.md
