### ISSUE TITLE
Building fuzzer error

### ISSUE THREAD

**Issue by TheCrott** [facebook/zstd#2766]
**Describe the bug**
Error when building fuzzer. I'm on ubuntu 20.04 with llvm 12 pre-built binaries, gcc 10.3

**To Reproduce**
1. clone zstd
2. cd to `zstd/tests/fuzz` and run `CC=clang CXX=clang++ ./fuzz.py build all --enable-fuzzer --enable-asan --enable-ubsan`
3. Wait until it show an error

**Screenshots and charts**
```sh
...
...
clang -I../../lib -I../../lib/common -I../../lib/compress -I../../lib/dictBuilder -I../../lib/deprecated -I../../lib/legacy -I../../contrib/seekable_format -I../../programs -DZSTD_MULTITHREAD -DZSTD_LEGACY_SUPPORT=1 -DDEBUGLEVEL=1 -DMEM_FORCE_MEMORY_ACCESS=0 -DFUZZ_RNG_SEED_SIZE=4 -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -Wall -Wextra -Wcast-qual -Wcast-align -Wshadow -Wstrict-aliasing=1 -Wswitch-enum -Wdeclaration-after-statement -Wstrict-prototypes -Wundef -Wvla -Wformat=2 -Winit-self -Wfloat-equal -Wwrite-strings -Wredundant-decls -g -fno-omit-frame-pointer -O3 -fsanitize=fuzzer -fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-sanitize=pointer-overflow -DFUZZING_ASSERT_VALID_SEQUENCE huf_round_trip.c -c -o rt_fuzz_huf_round_trip.o
ar rv libregression.a d_fuzz_regression_driver.o
ar: creating libregression.a
a - d_fuzz_regression_driver.o

make: *** [Makefile:136: d_lib_compress_zstd_lazy.o] Killed
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "fuzz.py", line 893, in <module>
    sys.exit(main())
  File "fuzz.py", line 872, in main
    return build(args)
  File "fuzz.py", line 493, in build
    subprocess.check_call(build_cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'CC=clang', 'CXX=clang++', 'CPPFLAGS=-DDEBUGLEVEL=1 -DMEM_FORCE_MEMORY_ACCESS=0 -DFUZZ_RNG_SEED_SIZE=4 -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION', 'CFLAGS=-O3 -fsanitize=fuzzer -fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-sanitize=pointer-overflow', 'CXXFLAGS=-O3 -fsanitize=fuzzer -fno-sanitize-recover=all -fsanitize=address -fsanitize=undefined -fno-sanitize=pointer-overflow', 'LDFLAGS=', '-j', 'LIB_FUZZING_ENGINE=', 'all']' returned non-zero exit status 2.
```

**Comment by Cyan4973** [comment]
Tried exactly the same command, on same OS and same compiler, and it completed successfully.

How much RAM does your system have access to ?
Could it be OOM-Killer related ?
