### ISSUE TITLE
HIST_count_wksp segment fault 

### ISSUE THREAD

**Issue by ShenglongWang** [facebook/zstd#3156]
when use zstd 1.3.5, core dump

(gdb) bt
#0 0x00007f5ed319aef8 in ?? () from /lib64/libgcc s.so.1
#1 0x00007f5ed319c039 in Unwind Backtrace () from /lib64/libgec_s.so.1
#2 0x00007f5ed383e5a6 in backtrace () from /l1ib64/libc.so.6
#3 0x000055fe6ef96f27 in print_call link ()
#4 0x000055fe6ef973c0 in sigsegv handler ()
#5 <signal handler called>
#6 0x00007f5ed3f519f0 in HIST_count_wksp () from /opt/libzstd.so.1
#7 0x00000000000000f4 ?? ()
#8 0x00007f570905f200 in ?? ()
#9 0x00007f570905e010 in ?? ()
#10 0x00007f570905f208 in ?? ()
#11 0x0000000000000003 in ?? ()
#12 0x00007f5ed3f5af60 in ZSTD_compressBlock_internal () from /opt/libzstd.so.1
#13 0x00007f5ed3f5dla3 in ZSTD_compressContinue_internal  () from /opt/libzstd. 5o.1
#14 0x00007f5ed3f5dacl in ZSTD compressContinue () from /opt/libzstd.so.1
#15 0x00007f5ed3f6619b in ZSTD_compressStream () from /opt/libzstd.so.1

please help me~~~~

**Comment by ShenglongWang** [comment]
the libzstd.so was damaged. md5 has beend changed。
