### ISSUE TITLE
fuzzer crash in FUZZ_setRandomParameters

### ISSUE THREAD

**Issue by enh-google** [facebook/zstd#3315]
**Describe the bug**

we (Android) saw a crash from your `tests/fuzz/stream_round_trip.c` fuzzer:
```


[Environment] Build fingerprint: google/flame_hwasan/flame:UpsideDownCake/MASTER/9218449:userdebug/dev-keys
--
  | [Environment] Patch level: 2022-12-05
  | [Environment] Local properties file "/data/local.prop" with contents:
  | None
  | +----------------------------------------Release Build Stacktrace----------------------------------------+
  | Command: /tradefed/adb shell UBSAN_OPTIONS=handle_abort=1 /data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/zstd_stream_round_trip_fuzzer -rss_limit_mb=2560 -timeout=90 -runs=100 /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-b407127da121797cb2ec6ad845adca48db5e86a3
  | Time ran: 0.16540098190307617
  |  
  | INFO: Running with entropic power schedule (0xFF, 100).
  | INFO: Seed:4116684403
  | INFO: Loaded 2 modules   (37383 inline 8-bit counters): 14042 [0x799d18df20, 0x799d1915fa), 23341 [0x6515acd768, 0x6515ad3295),
  | INFO: Loaded 2 PC tables (37383 PCs): 14042 [0x799d191600,0x799d1c83a0), 23341 [0x6515ad3298,0x6515b2e568),
  | /data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/zstd_stream_round_trip_fuzzer: Running 1 inputs 100 time(s) each.
  | Running: /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-b407127da121797cb2ec6ad845adca48db5e86a3
  | external/zstd/tests/fuzz/zstd_helpers.c: 26: Assertion: `!ZSTD_isError(ZSTD_CCtx_setParameter(cctx, param, value))' failed. Unsupported parameter
  | HWAddressSanitizer:DEADLYSIGNAL
  | ==9926==ERROR: HWAddressSanitizer: ABRT on unknown address 0x0000000026c6 (pc 0x0079a02cb4e0 bp 0x007fd9a3d2e0 sp 0x007fd9a3d220 T9926)
  | libunwind: unsupported .eh_frame_hdr version: 127 at 79a7266000
  | #0 0x79a02cb4e0 in abort bionic/libc/bionic/abort.cpp:49:22
  | #1 0x65159235e4 in set external/zstd/tests/fuzz/zstd_helpers.c:26:5
  | #2 0x65159235e4 in setRand external/zstd/tests/fuzz/zstd_helpers.c:32:5
  | #3 0x6515922fe0 in FUZZ_setRandomParameters external/zstd/tests/fuzz/zstd_helpers.c:92:5
  | #4 0x65159238b0 in compress external/zstd/tests/fuzz/stream_round_trip.c:64:5
  | #5 0x65159238b0 in LLVMFuzzerTestOneInput external/zstd/tests/fuzz/stream_round_trip.c:163:30
  | #6 0x6515936290 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:612:13
  | #7 0x651592ac74 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
  | #8 0x651592fc2c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
  | #9 0x65159570fc in main out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #10 0x79a02c0820 in __libc_init bionic/libc/bionic/libc_init_dynamic.cpp:159:8
  |  
  | HWAddressSanitizer can not provide additional info.
  | SUMMARY: HWAddressSanitizer: ABRT (/data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/lib/libc.so+0x654e0) (BuildId: 5ef08c2727c03ae4418e9d488478ca20)
  | ==9926==ABORTING
  | Aborted


<br class="Apple-interchange-newline">[Environment] Build fingerprint: google/flame_hwasan/flame:UpsideDownCake/MASTER/9218449:userdebug/dev-keys
[Environment] Patch level: 2022-12-05
[Environment] Local properties file "/data/local.prop" with contents:
None
+----------------------------------------Release Build Stacktrace----------------------------------------+
Command: /tradefed/adb shell UBSAN_OPTIONS=handle_abort=1 /data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/zstd_stream_round_trip_fuzzer -rss_limit_mb=2560 -timeout=90 -runs=100 /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-b407127da121797cb2ec6ad845adca48db5e86a3
Time ran: 0.16540098190307617
INFO: Running with entropic power schedule (0xFF, 100).
INFO: [Seed:4116684403](https://cs.corp.google.com/android/Seed?rcl=9255721&l=4116684403)
INFO: Loaded 2 modules   (37383 inline 8-bit counters): 14042 [0x799d18df20, 0x799d1915fa), 23341 [0x6515acd768, 0x6515ad3295),
INFO: Loaded 2 PC tables (37383 PCs): 14042 [0x799d191600,0x799d1c83a0), 23341 [0x6515ad3298,0x6515b2e568),
/data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/zstd_stream_round_trip_fuzzer: Running 1 inputs 100 time(s) each.
Running: /data/fuzz/bot/clusterfuzz/bot/inputs/fuzzer-testcases/crash-b407127da121797cb2ec6ad845adca48db5e86a3
external/zstd/tests/fuzz/zstd_helpers.c: 26: Assertion: `!ZSTD_isError(ZSTD_CCtx_setParameter(cctx, param, value))' failed. Unsupported parameter
HWAddressSanitizer:DEADLYSIGNAL
==9926==ERROR: HWAddressSanitizer: ABRT on unknown address 0x0000000026c6 (pc 0x0079a02cb4e0 bp 0x007fd9a3d2e0 sp 0x007fd9a3d220 T9926)
libunwind: unsupported .eh_frame_hdr version: 127 at 79a7266000
    #0 0x79a02cb4e0 in abort [bionic/libc/bionic/abort.cpp:49](https://cs.corp.google.com/android/bionic/libc/bionic/abort.cpp?rcl=334ffdc40b2bc92c5352c45abc0620de8648836d&l=49):22
    #1 0x65159235e4 in set [external/zstd/tests/fuzz/zstd_helpers.c:26](https://cs.corp.google.com/android/external/zstd/tests/fuzz/zstd_helpers.c?rcl=ebc8714f1ac084791081f0c1f8f8e2ed8fd577b4&l=26):5
    #2 0x65159235e4 in setRand [external/zstd/tests/fuzz/zstd_helpers.c:32](https://cs.corp.google.com/android/external/zstd/tests/fuzz/zstd_helpers.c?rcl=ebc8714f1ac084791081f0c1f8f8e2ed8fd577b4&l=32):5
    #3 0x6515922fe0 in FUZZ_setRandomParameters [external/zstd/tests/fuzz/zstd_helpers.c:92](https://cs.corp.google.com/android/external/zstd/tests/fuzz/zstd_helpers.c?rcl=ebc8714f1ac084791081f0c1f8f8e2ed8fd577b4&l=92):5
    #4 0x65159238b0 in compress [external/zstd/tests/fuzz/stream_round_trip.c:64](https://cs.corp.google.com/android/external/zstd/tests/fuzz/stream_round_trip.c?rcl=ebc8714f1ac084791081f0c1f8f8e2ed8fd577b4&l=64):5
    #5 0x65159238b0 in LLVMFuzzerTestOneInput [external/zstd/tests/fuzz/stream_round_trip.c:163](https://cs.corp.google.com/android/external/zstd/tests/fuzz/stream_round_trip.c?rcl=ebc8714f1ac084791081f0c1f8f8e2ed8fd577b4&l=163):30
    #6 0x6515936290 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) [out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:612](https://cs.corp.google.com/android/out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp?rcl=9255721&l=612):13
    #7 0x651592ac74 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) [out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324](https://cs.corp.google.com/android/out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp?rcl=9255721&l=324):6
    #8 0x651592fc2c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) [out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860](https://cs.corp.google.com/android/out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp?rcl=9255721&l=860):9
    #9 0x65159570fc in main [out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20](https://cs.corp.google.com/android/out/lib/compiler-rt-aarch64/out/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp?rcl=9255721&l=20):10
    #10 0x79a02c0820 in __libc_init [bionic/libc/bionic/libc_init_dynamic.cpp:159](https://cs.corp.google.com/android/bionic/libc/bionic/libc_init_dynamic.cpp?rcl=334ffdc40b2bc92c5352c45abc0620de8648836d&l=159):8
HWAddressSanitizer can not provide additional info.
SUMMARY: HWAddressSanitizer: ABRT (/data/fuzz/bot/builds/android-haiku_target_hwasan_zstd_stream_round_trip_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/lib/libc.so+0x654e0) (BuildId: 5ef08c2727c03ae4418e9d488478ca20)
==9926==ABORTING
Aborted
```
[clusterfuzz-testcase-minimized-zstd_stream_round_trip_fuzzer-5757473591263232.gz](https://github.com/facebook/zstd/files/10007902/clusterfuzz-testcase-minimized-zstd_stream_round_trip_fuzzer-5757473591263232.gz)

**To Reproduce**

this was with version "v1.5.2".

**Desktop (please complete the following information):**
Android arm64 (running a hwasan build).

**Comment by danlark1** [comment]
Fixed in https://github.com/facebook/zstd/pull/3291
